// <auto-generated />
using System;
using EscalaGcm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscalaGcm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212163704_AddRetAndEvento")]
    partial class AddRetAndEvento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Ausencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuardaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuardaId", "DataInicio", "DataFim");

                    b.ToTable("ausencias", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("equipes", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.EquipeMembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuardaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuardaId");

                    b.HasIndex("EquipeId", "GuardaId")
                        .IsUnique();

                    b.ToTable("equipe_membros", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quinzena")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ano", "Mes", "Quinzena", "SetorId")
                        .IsUnique();

                    b.HasIndex("SetorId", "Ano", "Mes", "Quinzena");

                    b.ToTable("escalas", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.EscalaAlocacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscalaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuardaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViaturaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EscalaItemId");

                    b.HasIndex("ViaturaId");

                    b.HasIndex("EquipeId", "EscalaItemId");

                    b.HasIndex("GuardaId", "EscalaItemId");

                    b.ToTable("escala_alocacoes", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.EscalaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("EscalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("EscalaId", "Data");

                    b.HasIndex("EscalaId", "Data", "TurnoId", "HorarioId")
                        .IsUnique();

                    b.ToTable("escala_itens", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataInicio", "DataFim");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Ferias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuardaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuardaId", "DataInicio", "DataFim");

                    b.ToTable("ferias", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Guarda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PosicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.HasIndex("PosicaoId");

                    b.ToTable("guardas", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Inicio", "Fim")
                        .IsUnique();

                    b.ToTable("horarios", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("posicoes", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Ret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuardaId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("HorarioFim")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HorarioInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("GuardaId", "Data");

                    b.ToTable("rets", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("setores", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("turnos", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Viatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.ToTable("viaturas", (string)null);
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Ausencia", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Guarda", "Guarda")
                        .WithMany("Ausencias")
                        .HasForeignKey("GuardaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guarda");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.EquipeMembro", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Membros")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaGcm.Domain.Entities.Guarda", "Guarda")
                        .WithMany("EquipeMembros")
                        .HasForeignKey("GuardaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Guarda");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Escala", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Setor", "Setor")
                        .WithMany("Escalas")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.EscalaAlocacao", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Alocacoes")
                        .HasForeignKey("EquipeId");

                    b.HasOne("EscalaGcm.Domain.Entities.EscalaItem", "EscalaItem")
                        .WithMany("Alocacoes")
                        .HasForeignKey("EscalaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaGcm.Domain.Entities.Guarda", "Guarda")
                        .WithMany("Alocacoes")
                        .HasForeignKey("GuardaId");

                    b.HasOne("EscalaGcm.Domain.Entities.Viatura", "Viatura")
                        .WithMany("Alocacoes")
                        .HasForeignKey("ViaturaId");

                    b.Navigation("Equipe");

                    b.Navigation("EscalaItem");

                    b.Navigation("Guarda");

                    b.Navigation("Viatura");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.EscalaItem", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Escala", "Escala")
                        .WithMany("Itens")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaGcm.Domain.Entities.Horario", "Horario")
                        .WithMany("EscalaItens")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaGcm.Domain.Entities.Turno", "Turno")
                        .WithMany("EscalaItens")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Horario");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Ferias", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Guarda", "Guarda")
                        .WithMany("Ferias")
                        .HasForeignKey("GuardaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guarda");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Guarda", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Posicao", "Posicao")
                        .WithMany("Guardas")
                        .HasForeignKey("PosicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posicao");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Ret", b =>
                {
                    b.HasOne("EscalaGcm.Domain.Entities.Evento", "Evento")
                        .WithMany("Rets")
                        .HasForeignKey("EventoId");

                    b.HasOne("EscalaGcm.Domain.Entities.Guarda", "Guarda")
                        .WithMany("Rets")
                        .HasForeignKey("GuardaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Guarda");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("Alocacoes");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Escala", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.EscalaItem", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Evento", b =>
                {
                    b.Navigation("Rets");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Guarda", b =>
                {
                    b.Navigation("Alocacoes");

                    b.Navigation("Ausencias");

                    b.Navigation("EquipeMembros");

                    b.Navigation("Ferias");

                    b.Navigation("Rets");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Horario", b =>
                {
                    b.Navigation("EscalaItens");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Posicao", b =>
                {
                    b.Navigation("Guardas");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Setor", b =>
                {
                    b.Navigation("Escalas");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Turno", b =>
                {
                    b.Navigation("EscalaItens");
                });

            modelBuilder.Entity("EscalaGcm.Domain.Entities.Viatura", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
